[
  {
    "id": "1",
    "materia": "Seguridad Social",
    "tema": "Altas",
    "situacion": "Formas parte del departamento laboral. Una persona empieza a trabajar hoy a las 9:00 y descubres a primera hora que el alta no ha sido tramitada.",
    "pregunta": "¿Qué actuación deberías realizar de forma inmediata?",
    "opcion_a": "Tramitar el alta cuanto antes, aunque la persona ya haya iniciado la actividad.",
    "opcion_b": "Esperar al cierre de mes y regularizarlo con la nómina.",
    "opcion_c": "No actuar hasta revisar toda la documentación contractual.",
    "opcion_d": "Comunicar la incidencia al trabajador y dejar constancia interna.",
    "respuesta_correcta": "A",
    "feedback_correcto": "La actuación correcta es tramitar el alta de forma inmediata. Aunque el inicio ya se haya producido, la empresa debe regularizar cuanto antes una situación que nunca debió empezar sin alta previa.",
    "feedback_error": "El error es retrasar la regularización o limitarse a una comunicación interna. Cuando falta el alta, la prioridad es corregir de inmediato la situación administrativa.",
    "referencia_legal": "Ley General de la Seguridad Social – alta previa al inicio de la actividad."
  },
  {
    "id": "2",
    "materia": "Seguridad Social",
    "tema": "Afiliación",
    "situacion": "Se incorpora una persona que ya ha trabajado antes en otras empresas y te preguntan si hay que volver a afiliarla.",
    "pregunta": "¿Qué trámite corresponde realmente?",
    "opcion_a": "Solicitar una nueva afiliación porque cambia de empresa.",
    "opcion_b": "Comprobar su situación y tramitar únicamente el alta si procede.",
    "opcion_c": "Esperar a la primera nómina para verificar si ya consta en el sistema.",
    "opcion_d": "Dar por hecho que la anterior empresa mantiene la afiliación activa.",
    "respuesta_correcta": "B",
    "feedback_correcto": "La afiliación es única para toda la vida laboral. Si la persona ya está afiliada, lo que corresponde en la nueva empresa es tramitar el alta, no una nueva afiliación.",
    "feedback_error": "El error es confundir afiliación con alta o dejar el trámite para más adelante. La empresa debe identificar la situación real y cursar el alta correspondiente.",
    "referencia_legal": "Ley General de la Seguridad Social – afiliación única y altas sucesivas."
  },
  {
    "id": "3",
    "materia": "Seguridad Social",
    "tema": "Bajas",
    "situacion": "Un contrato temporal finaliza este viernes y el responsable del área te dice que no hace falta tocar nada porque la relación ya se extingue sola.",
    "pregunta": "¿Qué deberías hacer?",
    "opcion_a": "No hacer ninguna actuación, porque el contrato ya terminó.",
    "opcion_b": "Comunicar la baja en Seguridad Social al finalizar la relación laboral.",
    "opcion_c": "Esperar a ver si la persona vuelve a ser contratada la semana siguiente.",
    "opcion_d": "Limitarte a enviar el finiquito y archivar el expediente.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Cuando cesa la relación laboral, la empresa debe comunicar la baja. La finalización del contrato no sustituye por sí sola el deber de comunicar el cese.",
    "feedback_error": "El error es pensar que el fin del contrato elimina la obligación administrativa de baja. Son actuaciones relacionadas, pero no equivalentes.",
    "referencia_legal": "Ley General de la Seguridad Social – obligación de comunicar bajas."
  },
  {
    "id": "4",
    "materia": "Seguridad Social",
    "tema": "Variaciones",
    "situacion": "Una persona pasa de jornada completa a jornada parcial a partir del próximo mes y la empresa quiere reflejarlo solo en nómina.",
    "pregunta": "¿Qué actuación es la más correcta?",
    "opcion_a": "Reflejar el cambio solo en nómina porque no afecta a Seguridad Social.",
    "opcion_b": "Comunicar la variación de datos correspondiente.",
    "opcion_c": "Dar de baja al trabajador y tramitar un alta nueva.",
    "opcion_d": "Esperar al cierre trimestral para informar del cambio.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Las modificaciones relevantes de la relación laboral, como la jornada, deben comunicarse como variación de datos. No basta con reflejarlas internamente.",
    "feedback_error": "El error es no comunicar el cambio o transformarlo en una baja y alta innecesarias. La vía correcta es la variación de datos.",
    "referencia_legal": "Normativa de afiliación y variaciones de datos en Seguridad Social."
  },
  {
    "id": "5",
    "materia": "Seguridad Social",
    "tema": "Cotización",
    "situacion": "Detectas que una persona ha estado prestando servicios, pero no se ha incluido correctamente en la cotización del mes.",
    "pregunta": "¿Qué criterio debe aplicar la empresa?",
    "opcion_a": "Esperar a una revisión externa antes de actuar.",
    "opcion_b": "Regularizar la situación e ingresar las diferencias que procedan.",
    "opcion_c": "Compensarlo en los meses siguientes sin comunicarlo.",
    "opcion_d": "Solicitar al trabajador que asuma la diferencia en su próxima nómina.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Si existe una diferencia de cotización, la empresa debe regularizarla. La obligación de cotizar no desaparece por el hecho de haber cometido un error previo.",
    "feedback_error": "El error es aplazar la regularización, compensarla de forma informal o trasladar al trabajador una obligación que corresponde a la empresa.",
    "referencia_legal": "Ley General de la Seguridad Social – obligación de cotizar e ingreso de cuotas."
  },
  {
    "id": "6",
    "materia": "Seguridad Social",
    "tema": "Recaudación",
    "situacion": "La empresa no ha ingresado las cuotas dentro del plazo reglamentario y pregunta si basta con pagar más tarde sin más consecuencias.",
    "pregunta": "¿Qué respuesta deberías dar?",
    "opcion_a": "Que puede ingresar cuando quiera sin efectos añadidos.",
    "opcion_b": "Que el ingreso fuera de plazo puede generar recargos.",
    "opcion_c": "Que solo habrá consecuencias si lo reclama el trabajador.",
    "opcion_d": "Que basta con justificar internamente el retraso.",
    "respuesta_correcta": "B",
    "feedback_correcto": "El ingreso fuera de plazo no es neutro: puede generar recargos y otras consecuencias recaudatorias. La empresa debe anticipar ese efecto.",
    "feedback_error": "El error es trivializar el retraso o tratarlo como una simple incidencia interna sin efectos jurídicos.",
    "referencia_legal": "Normativa recaudatoria de la Seguridad Social – recargos por ingreso fuera de plazo."
  },
  {
    "id": "7",
    "materia": "Laboral",
    "tema": "Contratación",
    "situacion": "Una persona va a incorporarse mañana y el responsable propone que empiece a trabajar mientras luego se termina la documentación.",
    "pregunta": "¿Qué decisión es la más adecuada?",
    "opcion_a": "Permitir la incorporación y completar la documentación cuando sea posible.",
    "opcion_b": "Asegurar antes de la incorporación la formalización contractual y las gestiones administrativas necesarias.",
    "opcion_c": "Dejar que empiece y firmar el contrato a final de semana.",
    "opcion_d": "Esperar solo a que el trabajador confirme verbalmente las condiciones.",
    "respuesta_correcta": "B",
    "feedback_correcto": "La incorporación debe prepararse correctamente antes del inicio efectivo. La empresa no debería normalizar que la documentación se resuelva una vez comenzada la actividad.",
    "feedback_error": "El error es convertir una urgencia operativa en una práctica habitual sin cobertura formal suficiente.",
    "referencia_legal": "Estatuto de los Trabajadores y normativa de Seguridad Social aplicable al inicio de la relación laboral."
  },
  {
    "id": "8",
    "materia": "Laboral",
    "tema": "Periodo de prueba",
    "situacion": "Un mando intermedio te dice que, como la persona está en periodo de prueba, no hace falta preocuparse demasiado por la formalización del proceso.",
    "pregunta": "¿Qué interpretación es correcta?",
    "opcion_a": "El periodo de prueba elimina las obligaciones formales de la empresa.",
    "opcion_b": "El periodo de prueba permite cualquier decisión sin marco jurídico.",
    "opcion_c": "El periodo de prueba no elimina las obligaciones formales ni administrativas de la relación laboral.",
    "opcion_d": "Durante el periodo de prueba no hace falta contrato si existe acuerdo verbal.",
    "respuesta_correcta": "C",
    "feedback_correcto": "El periodo de prueba no suspende las obligaciones formales ni administrativas. La relación laboral existe y debe estar correctamente documentada y gestionada.",
    "feedback_error": "El error es pensar que el periodo de prueba funciona como una zona libre de reglas o formalidades.",
    "referencia_legal": "Estatuto de los Trabajadores – periodo de prueba."
  },
  {
    "id": "9",
    "materia": "Laboral",
    "tema": "Jornada",
    "situacion": "Un responsable modifica de hecho la jornada de una persona para adaptarla a necesidades del servicio, pero no comunica el cambio ni revisa su encaje.",
    "pregunta": "¿Qué problema principal detectas?",
    "opcion_a": "Ninguno, si el cambio mejora la organización interna.",
    "opcion_b": "Que una modificación de jornada no debe improvisarse sin revisar su tratamiento y comunicación.",
    "opcion_c": "Que solo hay problema si el trabajador presenta una queja formal.",
    "opcion_d": "Que basta con reflejar el cambio en el calendario interno.",
    "respuesta_correcta": "B",
    "feedback_correcto": "La jornada no debería modificarse de hecho sin revisar el marco aplicable y la forma de documentar la decisión. La organización interna no sustituye el cumplimiento.",
    "feedback_error": "El error es tratar la jornada como una cuestión puramente interna sin relevancia jurídica ni necesidad de control.",
    "referencia_legal": "Estatuto de los Trabajadores – jornada y tiempo de trabajo."
  },
  {
    "id": "10",
    "materia": "Seguridad Social",
    "tema": "Altas",
    "situacion": "La empresa tramita el alta el mismo día de inicio, pero después de que la persona ya haya comenzado a trabajar.",
    "pregunta": "¿Cuál es la valoración correcta?",
    "opcion_a": "Es válido porque se ha comunicado dentro del mismo día.",
    "opcion_b": "Es correcto si el contrato ya estaba firmado.",
    "opcion_c": "No es correcto, porque el alta debe ser previa al inicio efectivo.",
    "opcion_d": "Solo sería incorrecto si la jornada fuera completa.",
    "respuesta_correcta": "C",
    "feedback_correcto": "La alta debe ser previa al inicio real de la actividad. Que se haya comunicado más tarde el mismo día no elimina el incumplimiento inicial.",
    "feedback_error": "El error es confundir rapidez posterior con cumplimiento previo. Lo exigible es que la situación esté regularizada antes de empezar a trabajar.",
    "referencia_legal": "Ley General de la Seguridad Social – alta previa."
  },
  {
    "id": "11",
    "materia": "Seguridad Social",
    "tema": "Variaciones",
    "situacion": "Se actualiza el salario de un trabajador, pero desde administración se plantea dejar el cambio solo reflejado en nómina interna.",
    "pregunta": "¿Qué actuación es la más adecuada?",
    "opcion_a": "Basta con reflejar el cambio en nómina.",
    "opcion_b": "Debe valorarse y, en su caso, comunicarse la variación correspondiente.",
    "opcion_c": "No debe hacerse nada hasta que cambie también la jornada.",
    "opcion_d": "Solo debe comunicarse si lo solicita el trabajador.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Los cambios relevantes deben revisarse desde el punto de vista administrativo y no limitarse a un ajuste interno de nómina.",
    "feedback_error": "El error es considerar que una modificación económica solo tiene efectos internos y no puede requerir actualización administrativa.",
    "referencia_legal": "Normativa de Seguridad Social sobre variaciones de datos."
  },
  {
    "id": "12",
    "materia": "Seguridad Social",
    "tema": "Deuda",
    "situacion": "La empresa acumula una deuda con la Seguridad Social y alguien propone no hacer nada hasta recibir una notificación formal.",
    "pregunta": "¿Qué enfoque es más correcto?",
    "opcion_a": "Esperar siempre a la reclamación formal antes de actuar.",
    "opcion_b": "Revisar de inmediato la situación y preparar la regularización o respuesta correspondiente.",
    "opcion_c": "Ignorar la deuda hasta el siguiente trimestre.",
    "opcion_d": "Trasladar el problema al trabajador afectado.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Cuando existe una incidencia de deuda, la empresa no debería adoptar una actitud pasiva. Lo adecuado es revisar la situación y anticipar la respuesta procedente.",
    "feedback_error": "El error es dejar evolucionar la incidencia sin control, como si la falta de actuación redujera el riesgo jurídico o económico.",
    "referencia_legal": "Normativa recaudatoria de la Seguridad Social – reclamación de deuda y actuaciones posteriores."
  },
  {
    "id": "13",
    "materia": "Laboral",
    "tema": "Tiempo parcial",
    "situacion": "Una persona contratada a tiempo parcial empieza a hacer de forma habitual más horas de las previstas, sin control formal suficiente.",
    "pregunta": "¿Qué deberías revisar primero?",
    "opcion_a": "Si la situación encaja con el régimen aplicable y con el control exigible.",
    "opcion_b": "Solo si el trabajador está conforme verbalmente.",
    "opcion_c": "Si el responsable necesita mantener ese ritmo unas semanas más.",
    "opcion_d": "Nada, porque mientras se paguen las horas no hay problema.",
    "respuesta_correcta": "A",
    "feedback_correcto": "En el trabajo a tiempo parcial, el control y el encaje jurídico del tiempo de trabajo son esenciales. No basta con una conformidad informal.",
    "feedback_error": "El error es tratar el exceso de horas como una simple cuestión organizativa o retributiva, sin revisar el marco aplicable.",
    "referencia_legal": "Estatuto de los Trabajadores – trabajo a tiempo parcial."
  },
  {
    "id": "14",
    "materia": "Laboral",
    "tema": "Subcontratación",
    "situacion": "La empresa va a iniciar una contrata y desde operaciones preguntan si basta con firmar el acuerdo comercial con la otra empresa.",
    "pregunta": "¿Qué criterio es más prudente?",
    "opcion_a": "Basta con el acuerdo mercantil si el servicio empieza pronto.",
    "opcion_b": "Antes de iniciar la contrata conviene verificar también las obligaciones laborales y de Seguridad Social que resulten exigibles.",
    "opcion_c": "No debe revisarse nada hasta que surja una incidencia.",
    "opcion_d": "La responsabilidad es siempre exclusiva de la contratista, así que no hace falta comprobación.",
    "respuesta_correcta": "B",
    "feedback_correcto": "En contratas y subcontratas, la revisión no debería limitarse al plano comercial. Es prudente comprobar también las obligaciones laborales y de Seguridad Social relevantes.",
    "feedback_error": "El error es reducir la contrata a un acuerdo mercantil y olvidar los deberes de verificación o control asociados.",
    "referencia_legal": "Estatuto de los Trabajadores – contratas y subcontratas."
  },
  {
    "id": "15",
    "materia": "Seguridad Social",
    "tema": "Responsable de cotización",
    "situacion": "En una reunión surge la duda de si el trabajador puede asumir por su cuenta el ingreso ordinario de las cuotas si la empresa tiene problemas de tesorería.",
    "pregunta": "¿Qué respuesta es correcta?",
    "opcion_a": "Sí, el trabajador puede sustituir a la empresa en el ingreso ordinario si ambos están de acuerdo.",
    "opcion_b": "No, la empresa sigue siendo la obligada principal en el ingreso de cuotas.",
    "opcion_c": "Solo ocurre así en contratos temporales.",
    "opcion_d": "Depende del salario mensual.",
    "respuesta_correcta": "B",
    "feedback_correcto": "La obligación principal de ingreso corresponde a la empresa. No se transforma en una carga ordinaria del trabajador por razones internas de tesorería.",
    "feedback_error": "El error es desplazar informalmente una obligación empresarial hacia el trabajador como si se tratara de un pacto válido.",
    "referencia_legal": "Ley General de la Seguridad Social – sujetos obligados y responsable del ingreso."
  },
  {
    "id": "16",
    "materia": "Laboral",
    "tema": "Extinción",
    "situacion": "Una relación laboral finaliza y el responsable propone dejar la documentación para más adelante porque la salida ya es conocida por todos.",
    "pregunta": "¿Qué deberías priorizar?",
    "opcion_a": "La gestión formal del cese y sus comunicaciones correspondientes.",
    "opcion_b": "Nada, porque si todos conocen la salida ya no hace falta documentar más.",
    "opcion_c": "Esperar a ver si la persona reclama algo.",
    "opcion_d": "Limitarse a devolver sus accesos internos.",
    "respuesta_correcta": "A",
    "feedback_correcto": "Cuando una relación finaliza, la empresa debe cerrar correctamente la gestión formal y administrativa del cese. El conocimiento interno no sustituye esa obligación.",
    "feedback_error": "El error es tratar una salida conocida como si ya estuviera jurídicamente cerrada sin más actuaciones.",
    "referencia_legal": "Estatuto de los Trabajadores y normativa administrativa vinculada al cese."
  },
  {
    "id": "17",
    "materia": "Seguridad Social",
    "tema": "Recaudación",
    "situacion": "Una empresa plantea ingresar solo parte de la deuda y dejar el resto pendiente indefinidamente hasta tener más liquidez.",
    "pregunta": "¿Qué análisis es más adecuado?",
    "opcion_a": "Es una solución suficiente sin efectos adicionales.",
    "opcion_b": "La empresa debe valorar que una deuda pendiente puede mantener consecuencias recaudatorias y exige una gestión activa.",
    "opcion_c": "No hay consecuencias mientras se pague una parte.",
    "opcion_d": "La deuda desaparece si se comunica internamente el problema.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Una deuda no desaparece por el hecho de atenderla parcialmente. La empresa debe gestionar activamente la situación y sus consecuencias recaudatorias.",
    "feedback_error": "El error es pensar que un pago parcial neutraliza por sí solo el problema o lo deja sin recorrido posterior.",
    "referencia_legal": "Normativa recaudatoria de la Seguridad Social."
  },
  {
    "id": "18",
    "materia": "Laboral",
    "tema": "Cambio de centro",
    "situacion": "Un trabajador pasa a prestar servicios en otro centro de trabajo y desde el área operativa se asume que basta con comunicarlo verbalmente.",
    "pregunta": "¿Qué deberías comprobar?",
    "opcion_a": "Si el cambio requiere tratamiento y actualización administrativa adecuada.",
    "opcion_b": "Nada, porque el cambio de centro es puramente interno.",
    "opcion_c": "Solo si cambia también el salario.",
    "opcion_d": "Solo si el trabajador se opone expresamente.",
    "respuesta_correcta": "A",
    "feedback_correcto": "Los cambios organizativos no siempre son neutros desde el punto de vista de gestión laboral. Deben revisarse y tratarse correctamente cuando proceda.",
    "feedback_error": "El error es dar por hecho que un cambio de centro nunca exige revisión administrativa o documental.",
    "referencia_legal": "Normativa laboral y administrativa aplicable a cambios relevantes en la relación laboral."
  },
  {
    "id": "19",
    "materia": "Seguridad Social",
    "tema": "Alta fuera de plazo",
    "situacion": "Tras detectar una falta de alta, alguien propone esperar unos días para reunir toda la documentación antes de hacer cualquier trámite.",
    "pregunta": "¿Qué enfoque es más correcto?",
    "opcion_a": "Esperar para presentar un expediente más completo.",
    "opcion_b": "Regularizar cuanto antes la situación administrativa y completar después lo necesario.",
    "opcion_c": "No hacer nada hasta recibir requerimiento.",
    "opcion_d": "Suspender toda actuación hasta que el trabajador firme una declaración interna.",
    "respuesta_correcta": "B",
    "feedback_correcto": "Ante una falta de alta, la prioridad es regularizar cuanto antes la situación. La perfección documental no debe utilizarse como excusa para retrasar la actuación básica.",
    "feedback_error": "El error es aplazar la regularización por razones organizativas internas, aumentando así el riesgo derivado del incumplimiento.",
    "referencia_legal": "Ley General de la Seguridad Social – alta y regularización."
  },
  {
    "id": "20",
    "materia": "Laboral",
    "tema": "Gestión operativa",
    "situacion": "Eres la persona de apoyo en el departamento laboral y recibes una incidencia urgente relacionada con incorporación, contrato y Seguridad Social, pero la información llega incompleta.",
    "pregunta": "¿Qué criterio de trabajo es más profesional?",
    "opcion_a": "Esperar a tener un expediente perfecto antes de actuar.",
    "opcion_b": "Identificar primero la obligación inmediata, asegurar la actuación crítica y completar después la revisión del resto.",
    "opcion_c": "Resolver solo la parte que te haya pedido el responsable directo, sin revisar implicaciones.",
    "opcion_d": "Dejar la incidencia para cuando haya menos carga de trabajo.",
    "respuesta_correcta": "B",
    "feedback_correcto": "En gestión laboral, muchas veces la clave está en priorizar bien: identificar la obligación inmediata crítica, asegurar su cumplimiento y después completar el resto de comprobaciones.",
    "feedback_error": "El error es no jerarquizar las actuaciones y permitir que una incidencia urgente permanezca abierta por falta de orden operativo.",
    "referencia_legal": "Criterio operativo derivado de obligaciones laborales y de Seguridad Social aplicables al caso."
  }
]
